# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/masaüstü/yazılımileilgilihersey/smartMaple/havadurumuScrubbing/sistemBaslat.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1045, 826)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.metoOfficeBaslat = QtWidgets.QPushButton(self.centralwidget)
        self.metoOfficeBaslat.setGeometry(QtCore.QRect(20, 110, 291, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.metoOfficeBaslat.setFont(font)
        self.metoOfficeBaslat.setObjectName("metoOfficeBaslat")
        self.weatherBaslat = QtWidgets.QPushButton(self.centralwidget)
        self.weatherBaslat.setGeometry(QtCore.QRect(350, 110, 291, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.weatherBaslat.setFont(font)
        self.weatherBaslat.setObjectName("weatherBaslat")
        self.HavadurumuxBaslat = QtWidgets.QPushButton(self.centralwidget)
        self.HavadurumuxBaslat.setGeometry(QtCore.QRect(680, 110, 331, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.HavadurumuxBaslat.setFont(font)
        self.HavadurumuxBaslat.setObjectName("HavadurumuxBaslat")
        self.metoOfficeLinkleriAl = QtWidgets.QPushButton(self.centralwidget)
        self.metoOfficeLinkleriAl.setGeometry(QtCore.QRect(10, 20, 301, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.metoOfficeLinkleriAl.setFont(font)
        self.metoOfficeLinkleriAl.setObjectName("metoOfficeLinkleriAl")
        self.weatherLinkleriAl = QtWidgets.QPushButton(self.centralwidget)
        self.weatherLinkleriAl.setGeometry(QtCore.QRect(340, 20, 301, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.weatherLinkleriAl.setFont(font)
        self.weatherLinkleriAl.setObjectName("weatherLinkleriAl")
        self.HavadurumuxLinkleriAl = QtWidgets.QPushButton(self.centralwidget)
        self.HavadurumuxLinkleriAl.setGeometry(QtCore.QRect(660, 20, 381, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.HavadurumuxLinkleriAl.setFont(font)
        self.HavadurumuxLinkleriAl.setObjectName("HavadurumuxLinkleriAl")
        self.metoOfficeDurdur = QtWidgets.QPushButton(self.centralwidget)
        self.metoOfficeDurdur.setGeometry(QtCore.QRect(20, 210, 291, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.metoOfficeDurdur.setFont(font)
        self.metoOfficeDurdur.setObjectName("metoOfficeDurdur")
        self.weatherDurdur = QtWidgets.QPushButton(self.centralwidget)
        self.weatherDurdur.setGeometry(QtCore.QRect(350, 210, 291, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.weatherDurdur.setFont(font)
        self.weatherDurdur.setObjectName("weatherDurdur")
        self.HavadurumuxDurdur = QtWidgets.QPushButton(self.centralwidget)
        self.HavadurumuxDurdur.setGeometry(QtCore.QRect(700, 210, 291, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.HavadurumuxDurdur.setFont(font)
        self.HavadurumuxDurdur.setObjectName("HavadurumuxDurdur")
        self.metoOfficeSonucu = QtWidgets.QLabel(self.centralwidget)
        self.metoOfficeSonucu.setGeometry(QtCore.QRect(20, 300, 291, 131))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.metoOfficeSonucu.setFont(font)
        self.metoOfficeSonucu.setObjectName("metoOfficeSonucu")
        self.weatherSonucu = QtWidgets.QLabel(self.centralwidget)
        self.weatherSonucu.setGeometry(QtCore.QRect(350, 310, 291, 131))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.weatherSonucu.setFont(font)
        self.weatherSonucu.setObjectName("weatherSonucu")
        self.HavadurumuxSonucu = QtWidgets.QLabel(self.centralwidget)
        self.HavadurumuxSonucu.setGeometry(QtCore.QRect(710, 300, 291, 131))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.HavadurumuxSonucu.setFont(font)
        self.HavadurumuxSonucu.setObjectName("HavadurumuxSonucu")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(310, 0, 20, 611))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(640, -10, 20, 611))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.metoCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.metoCheckBox.setEnabled(False)
        self.metoCheckBox.setGeometry(QtCore.QRect(20, 450, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.metoCheckBox.setFont(font)
        self.metoCheckBox.setObjectName("metoCheckBox")
        self.weatherCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.weatherCheckBox.setEnabled(False)
        self.weatherCheckBox.setGeometry(QtCore.QRect(340, 450, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.weatherCheckBox.setFont(font)
        self.weatherCheckBox.setObjectName("weatherCheckBox")
        self.havadurumuxCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.havadurumuxCheckBox.setEnabled(False)
        self.havadurumuxCheckBox.setGeometry(QtCore.QRect(670, 460, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.havadurumuxCheckBox.setFont(font)
        self.havadurumuxCheckBox.setObjectName("havadurumuxCheckBox")
        self.veriTabaninaYukle = QtWidgets.QPushButton(self.centralwidget)
        self.veriTabaninaYukle.setGeometry(QtCore.QRect(600, 620, 421, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.veriTabaninaYukle.setFont(font)
        self.veriTabaninaYukle.setObjectName("veriTabaninaYukle")
        self.butunSistemleriBaslat = QtWidgets.QPushButton(self.centralwidget)
        self.butunSistemleriBaslat.setGeometry(QtCore.QRect(20, 620, 421, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.butunSistemleriBaslat.setFont(font)
        self.butunSistemleriBaslat.setObjectName("butunSistemleriBaslat")
        self.butunSistemleriBaslat_2 = QtWidgets.QPushButton(self.centralwidget)
        self.butunSistemleriBaslat_2.setGeometry(QtCore.QRect(20, 710, 421, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.butunSistemleriBaslat_2.setFont(font)
        self.butunSistemleriBaslat_2.setObjectName("butunSistemleriBaslat_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.metoOfficeBaslat.setText(_translate("MainWindow", "Metoffice BAŞLAT"))
        self.weatherBaslat.setText(_translate("MainWindow", "Weather Başlat"))
        self.HavadurumuxBaslat.setText(_translate("MainWindow", "Havadurumux Başlat"))
        self.metoOfficeLinkleriAl.setText(_translate("MainWindow", "Metoffice Linkleri Al"))
        self.weatherLinkleriAl.setText(_translate("MainWindow", "Weather Linkleri Al"))
        self.HavadurumuxLinkleriAl.setText(_translate("MainWindow", "Havadurumux Linkleri Al"))
        self.metoOfficeDurdur.setText(_translate("MainWindow", "Durdur"))
        self.weatherDurdur.setText(_translate("MainWindow", "Durdur"))
        self.HavadurumuxDurdur.setText(_translate("MainWindow", "Durdur"))
        self.metoOfficeSonucu.setText(_translate("MainWindow", "işlemler"))
        self.weatherSonucu.setText(_translate("MainWindow", "işlemler"))
        self.HavadurumuxSonucu.setText(_translate("MainWindow", "işlemler"))
        self.metoCheckBox.setText(_translate("MainWindow", "Veriler Yazmaya Hazır Değil"))
        self.weatherCheckBox.setText(_translate("MainWindow", "Veriler Yazmaya Hazır Değil"))
        self.havadurumuxCheckBox.setText(_translate("MainWindow", "Veriler Yazmaya Hazır Değil"))
        self.veriTabaninaYukle.setText(_translate("MainWindow", "Veri Tabanına Kayıt Yap"))
        self.butunSistemleriBaslat.setText(_translate("MainWindow", "Butun Sistemleri Başlat"))
        self.butunSistemleriBaslat_2.setText(_translate("MainWindow", "Butun Sistemleri Durdur"))

